POST http://localhost:5000/auth/register
Content-Type: application/x-www-form-urlencoded

username=elcapiprice&firstname=Miguel&lastname=Medina&password=123456

###

POST http://localhost:5000/auth/register
Content-Type: application/x-www-form-urlencoded

username=sharon&firstname=Sharon&lastname=Medina&password=123456

###
